// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR9ipNAS1C3CO1rstSLF4DIzVAnJBevAQ',
    appId: '1:463618942793:web:da9a1610f44481fd3e9c98',
    messagingSenderId: '463618942793',
    projectId: 'my-company-group',
    authDomain: 'my-company-group.firebaseapp.com',
    storageBucket: 'my-company-group.appspot.com',
    measurementId: 'G-8FSLBBTVH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc-T_ibFqoeQII1sehA6dZ13TQ_aQoRcw',
    appId: '1:463618942793:android:5d212adbec5cee1a3e9c98',
    messagingSenderId: '463618942793',
    projectId: 'my-company-group',
    storageBucket: 'my-company-group.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-mYSJ-xDcRVI6dV4uL2ETE6RE3qZgvzo',
    appId: '1:463618942793:ios:2ce02d14b1d11ec13e9c98',
    messagingSenderId: '463618942793',
    projectId: 'my-company-group',
    storageBucket: 'my-company-group.appspot.com',
    iosBundleId: 'com.example.myCompany2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-mYSJ-xDcRVI6dV4uL2ETE6RE3qZgvzo',
    appId: '1:463618942793:ios:4116e5153bf737553e9c98',
    messagingSenderId: '463618942793',
    projectId: 'my-company-group',
    storageBucket: 'my-company-group.appspot.com',
    iosBundleId: 'com.example.myCompany2.RunnerTests',
  );
}
